Ivy-Interactive/Ivy-Framework

Ivy.Docs/Docs/02_Widgets/01_Common/TextInput.md
This is my proposal (and also to demonstrate I can do it)
=> Istvan Izsak - proposal for working on docs for Ivy Framework

Ivy.Auth.Authelia/AutheliaAuthProvider.cs, Ivy.Auth.Supabase/SupabaseAuthProvider.cs, Ivy/AppHub.cs, Ivy/Apps/AppArgs.cs, Ivy/Auth/AuthController.cs, Ivy/Auth/AuthOption.cs, Ivy/Auth/AuthService.cs, Ivy/Auth/AuthToken.cs, Ivy/Auth/BasicAuthProvider.cs, Ivy/Auth/DefaultAuthApp.cs, Ivy/Auth/IAuthProvider.cs, Ivy/Auth/IAuthService.cs, Ivy/Client/ClientExtensions.cs, Ivy/Hooks/UseWebhook.cs, frontend/src/hooks/use-backend.ts
See also https://github.com/Ivy-Interactive/Ivy/pull/143, https://github.com/Ivy-Interactive/Ivy/issues/99
=> Finish Supabase Auth Provider

frontend/src/widgets/layouts/TabsLayoutWidget.tsx
Here is a QOL feature request: being able to close a tab without viewing it.
Before:
After:
Also original code is filled with useEffects used in conditional sections of code, which is react hook violation. I will address this here too
=> feat: close any tab

frontend/src/components/ui/checkbox.tsx, frontend/src/hooks/use-focus-management.ts
I have forgotten to remove this before.
=> chore / cleanup leftovers

Ivy.Samples/Apps/Widgets/Inputs/NumberInputApp.cs, frontend/src/components/ui/slider.tsx
Added currency numeric types
Added greyerod out horizontal line representing the full width of slider (for all sliders)
=> feat: currency numeric inputs

frontend/src/components/ui/dialog.tsx, frontend/src/widgets/dialogs/DialogBodyWidget.tsx
See video
Had to fix layout (we used grid), also some ARIA semantics and id' tracking needed to be looked at.
https://github.com/user-attachments/assets/4bc2bd47-19d1-48f8-b6f0-70d627c6918a
=> (forms): no scrollbar

Ivy.Samples/Apps/Widgets/Inputs/NumberInputApp.cs, Ivy/Widgets/Inputs/NumberInput.cs, frontend/src/components/NumberInput.tsx, frontend/src/widgets/inputs/NumberInputWidget.tsx
Added declaration of supported types
Added option to hide/show arrow controls
Also handling this edge case now 
And mouse drag triggers updates only on mouse release now
=> Number input polishing

.github/workflows/playwright.yml, frontend/src/components/ui/calendar.tsx, frontend/src/components/ui/chart.tsx, frontend/src/hoc/withTooltip.tsx, frontend/src/types/widgets.ts, frontend/src/widgets/DropDownMenuWidget.tsx, frontend/src/widgets/WidgetRenderer.tsx, frontend/src/widgets/charts/shared.ts, frontend/src/widgets/effects/AnimationWidget.tsx, frontend/src/widgets/inputs/TextInputWidget.tsx, frontend/src/widgets/internal/SidebarNewsWidget.tsx, frontend/src/widgets/layouts/GridLayoutWidget.tsx, frontend/src/widgets/layouts/ResizeablePanelGroupWidget.tsx, frontend/src/widgets/primitives/ArticleWidget.tsx, frontend/src/widgets/widgetMap.ts
Now we test whether the frontend builds in the pipeline.
Attempted to fix all the problems that came with this - as well as build issues.
------
Known issue from type mismatches:
We had some workaround in our code, with type assertions that broke after package upgrades. [Calendar view got broken over the updates. I will fix it in separate PR](https://github.com/Ivy-Interactive/Ivy-Framework/issues/101)
=> FE build health check

frontend/src/components/ui/slider.tsx, frontend/src/widgets/inputs/NumberInputWidget.tsx
Implemented currency signs in slider labels
=> feat: number input shows currency via slider

Ivy.Docs/Docs/02_Widgets/02_Inputs/Select.md, Ivy/Widgets/Inputs/SelectInput.cs
I fixed the coffee example and resolved the issue we had.
=> feat: public select many to include it in json arrays

frontend/src/widgets/inputs/TextInputWidget.tsx
=> feat: implement clear search btn

Ivy.Docs/Docs/02_Widgets/02_Inputs/Number.md, Ivy/Core/Utils.cs, Ivy/Utils.cs, Ivy/Widgets/Inputs/NumberInput.cs, frontend/src/components/NumberInput.tsx, frontend/src/widgets/inputs/NumberInputWidget.tsx
Better min/maxes
Smarter step value
Fixed issue where x was rendered as invalid icon for some reason
=> feat: handle overflown values

Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/02_Installation.md
=> (docs): installation rework

Ivy.Docs/Helpers/TypeUtils.cs, Ivy.Docs/Helpers/WidgetDocsView.cs, Ivy/Widgets/Inputs/FeedbackInput.cs
Now: 
Before it would just be a single long col.
=> feat: better grid with supported types

Ivy.Docs.Tools/Utils.cs, Ivy.Docs/Ivy.Docs.csproj
This PR addresses issue of BE tests failing on MacOS
=> Draft: feat: get path for link cross-platform

Ivy.Samples/Apps/Widgets/Inputs/BoolInputApp.cs, frontend/e2e/bool-input.spec.ts, frontend/src/components/ui/toggle.tsx
Writing tests to bool-input variants grid
=> (tests): bool-input variants tests

Ivy.Samples/Apps/Widgets/Inputs/DateTimeInputApp.cs, Ivy/Widgets/Inputs/DateTimeInput.cs, frontend/src/widgets/inputs/DateTimeInputWidget.tsx
=> fix: unable to edit time in datetime

Ivy.Samples/Apps/Widgets/Inputs/FileInputApp.cs, Ivy/Widgets/Inputs/FileInput.cs, frontend/src/widgets/inputs/FileInputWidget.tsx
=> feat: file input size and format features

Ivy.Samples/Apps/Widgets/Charts/LineChartApp.cs, Ivy/Charts/LineChartView.cs
=> feat: line chart view expansion

frontend/src/app.css, frontend/src/components/ui/sidebar.tsx, frontend/src/widgets/layouts/SidebarLayoutWidget.tsx, frontend/src/widgets/primitives/IvyLogoWidget.tsx
=> feat: primary color for icons

Ivy.Docs/Docs/02_Widgets/03_Primitives/Html.md, frontend/src/components/EmojiRating.tsx, frontend/src/components/NumberInput.tsx, frontend/src/components/StarRating.tsx, frontend/src/components/ThumbsRating.tsx, frontend/src/components/ui/button.tsx, frontend/src/components/ui/checkbox.tsx, frontend/src/components/ui/radio-group.tsx, frontend/src/components/ui/select.tsx, frontend/src/components/ui/slider.tsx, frontend/src/components/ui/toggle.tsx, frontend/src/widgets/blades/BladeWidget.tsx, frontend/src/widgets/inputs/AsyncSelectInputWidget.tsx, frontend/src/widgets/inputs/CodeInputWidget.tsx, frontend/src/widgets/inputs/ColorInputWidget.tsx, frontend/src/widgets/inputs/DateRangeInputWidget.tsx, frontend/src/widgets/inputs/DateTimeInputWidget.tsx, frontend/src/widgets/inputs/FileInputWidget.tsx, frontend/src/widgets/inputs/SelectInputWidget.tsx, frontend/src/widgets/inputs/TextInputWidget.tsx, frontend/src/widgets/internal/DbmlCanvasWidget.tsx, frontend/src/widgets/layouts/TabsLayoutWidget.tsx, frontend/src/widgets/lists/ListItemWidget.tsx, frontend/src/widgets/lists/ListWidget.tsx, frontend/src/widgets/primitives/HtmlWidget.tsx, frontend/src/widgets/tables/TableCellWidget.tsx, frontend/src/widgets/tables/TableRowWidget.tsx
UI/UX changes around mouse events and theming with the aim of supporting dark theme.
=> feat: theming and cursor events

frontend/src/widgets/inputs/TextInputWidget.tsx
=> feat: fix text nullable invalid overlap

frontend/src/components/ui/button.tsx, frontend/src/components/ui/dialog.tsx, frontend/src/widgets/dialogs/DialogBodyWidget.tsx
=> Feat/form UI fixes

Ivy/Chrome/DefaultSidebarChrome.cs, frontend/src/widgets/layouts/SidebarLayoutWidget.tsx
=> feat: better handle empty search results

Ivy.Samples/Apps/Demos/DashboardApp.cs
=> fix: perfectly balanced

frontend/e2e/bool-input.spec.ts, frontend/e2e/date-time-input.spec.ts, frontend/e2e/number-input.spec.ts, frontend/e2e/smoke.spec.ts
@nielsbosma I used cursor and set up a playwright MCP server. 
On second attempt where I made the right prompt, it just fixed the tests in the intended way.
total time spent: 15 minutes
FYI here is the prompt:
```text
Hey.
I have e2e tests that I have skipping now. Before our solution used iframes, now we got rid of it.
We have a lot of retries that we added when we had iframes.
I want you to clean that shit up and remove the retries.
Then I want you to make the tests pass, 1 by 1.
After you fix each test, I want you to commit it. Make sure to from start switch to a new feature branch
=> do not merge: Cleanup e2e tests

Ivy.Samples/Apps/Widgets/Inputs/SelectInputApp.cs, frontend/src/components/ui/checkbox.tsx, frontend/src/components/ui/multiselect.tsx, frontend/src/widgets/inputs/SelectInputWidget.tsx
=> improve stylings for select list and checkboxes

Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/02_Installation.md, Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/03_Basics.md, Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/05_TodoTutorial.md, frontend/src/widgets/internal/TerminalWidget.tsx
=> (terminal): only add > to commands, not outputs

Ivy.Samples/Apps/Widgets/Effects/AnimationApp.cs
This will need more work.
https://github.com/user-attachments/assets/669fa087-fea3-405c-8a19-b3ebd01c7500
=> feat: some more baseline animations

frontend/src/widgets/blades/BladeWidget.tsx
=> improve icon positioning in products product view header

frontend/e2e/bool-input.spec.ts, frontend/e2e/date-time-input.spec.ts, frontend/e2e/number-input.spec.ts, frontend/src/widgets/layouts/SidebarLayoutWidget.tsx
okay radix pulled a sneaky one with making assumption that you should only have 1 sidebar per iframe.
So I am stripping our radix implementation so we have more control over the sidebar behavior.
=> feat: scrap radix sidebar, use house implementation

frontend/src/widgets/layouts/SidebarLayoutWidget.tsx
Reverts Ivy-Interactive/Ivy-Framework#311
=> Revert "chore: attempt to fix the sidebar toggle missing in deploy"

Ivy.Docs/Docs/02_Widgets/01_Common/Table.md, Ivy.Docs/GlobalUsings.cs
=> Implement documentation for Tables

Ivy.Docs/Docs/02_Widgets/03_Primitives/Avatar.md
=> feat: name changed

Ivy.Docs/Docs/02_Widgets/04_Layouts/TabsLayout.md
=> Tabs layout docs

Ivy/Server.cs
Reverts Ivy-Interactive/Ivy-Framework#380
=> Revert "feat: serve index page as fallback"

frontend/src/widgets/primitives/ArticleWidget.tsx
=> feat: remove green color from the text in the table of contents

frontend/src/widgets/SheetWidget.tsx
=> (docs): scrollbar not working in code source section

Ivy.Docs.Shared/Docs/02_Widgets/02_Inputs/Code.md
=> (docs): implement code input documentation

frontend/src/widgets/inputs/CodeInputWidget.css, frontend/src/widgets/inputs/CodeInputWidget.tsx
=> (code input): typescript and python colors implemented

.github/workflows/backend-checks-linux.yml, .github/workflows/backend-checks-windows.yml, .github/workflows/e2e-tests.yml, Ivy/Ivy.csproj, Ivy/Server.cs
fixed this.
Also made sure to include the right fe dist files.
Now we got errors when we build a BE without built FE. So you need to have frotnend dist stuff included.
If you just do a dotnet build in a fresh project, it will now raise an error, because you need to have build FE first,
=> feat: fix serve issues

Ivy/AppSessionStore.cs, Ivy/Tui/AnsiConsole.cs, Ivy/Tui/AnsiTable.cs
This pull request introduces improved, native console output formatting for in-terminal tables via two new classes: `AnsiTable` and `AnsiConsole` (added under `Ivy.Tui`). These replace the dependency on heavier third-party libraries like Spectre.Console for displaying tabular data in the console. The new functionality is now utilized in `AppSessionStore.Dump()`, which is invoked when showing session information (e.g., on CTRL+S).
- **Added `AnsiTable` class**  
Provides a lightweight, dependency-free way to create and render tables directly to the console using Unicode box-drawing characters and ANSI escape codes when available.
- **Added `AnsiConsole` class**  
Handles writing rendered tables to the console and ensures ANSI support is enabled (especially on Windows).
- **Refactored …
=> Add AnsiTable and AnsiConsole for improved session display in console

frontend/src/widgets/primitives/ArticleWidget.tsx
=> (docs): spacing is now gap 4

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Json.md, frontend/src/components/JsonRenderer.tsx
=> (docs): impelement Json documentation

Ivy.Docs.Shared/Docs/02_Widgets/07_Advanced/Sheet.md, frontend/src/lib/styles.ts
=> (docs): implement sheet documentation

frontend/src/hooks/use-backend.tsx, frontend/src/widgets/WidgetRenderer.tsx
this does not solve the issue.
It just makes so the page does not crash, and it provides more logging now. Real issue should be addressed at some point.
=> bug: better handle empty nodes

Ivy.Docs.Shared/Docs/02_Widgets/02_Inputs/Bool.md
=> (docs): delete example with dashboard in bool input doc

Ivy.Docs.Shared/Docs/02_Widgets/02_Inputs/Code.md, frontend/src/widgets/internal/DbmlCanvasWidget.css, frontend/src/widgets/internal/DbmlCanvasWidget.tsx
=> feat: improve dbml editor colors

Ivy.Docs.Shared/Docs/02_Widgets/04_Layouts/SidebarLayout.md
=> (docs): implement sidebar layout docs

Ivy.Docs.Shared/Docs/02_Widgets/04_Layouts/HeaderLayout.md, frontend/src/widgets/layouts/HeaderLayoutWidget.tsx
=> (docs): implement header layout doc

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Xml.md, frontend/src/components/XmlRenderer.tsx
=> (doc): implement xml documentation

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Svg.md
=> (doc): implement svg documentation

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Xml.md
=> (doc): delete redundant examples, add example section for xml doc

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Callout.md
=> (doc): implement Callout documentation

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Fragment.md
=> (doc): implement Fragment doc

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Error.md, frontend/src/components/ErrorDisplay.tsx
=> (doc): implement Error doc

Ivy.Docs.Shared/Docs/02_Widgets/01_Common/List.md
=> (docs): implement List doc

Ivy.Docs.Shared/Docs/02_Widgets/01_Common/Expandable.md, frontend/src/widgets/ExpandableWidget.tsx
=> (docs): implement Expandable doc

Ivy.Docs.Shared/Docs/01_Onboarding/02_Concepts/Signals.md, Ivy.Docs.Shared/Docs/01_Onboarding/02_Concepts/Widgets.md
Not finished yet
@rorychatt, need your opinion about this type of impelementation of this doc.
=> (docs): implement Widgets doc

Ivy/Core/AbstractWidget.cs, Ivy/Core/Hooks/HookExtensions.cs, Ivy/Core/Hooks/ViewContext.cs, Ivy/Views/Charts/PivotTable.cs, Ivy/Views/Charts/TableCalculations.cs, Ivy/Views/Forms/FormBuilder.cs, Ivy/Widgets/Internal/DbmlCanvas.cs, Ivy/Widgets/Internal/DemoBox.cs, Ivy/Widgets/Internal/IvyLogo.cs, Ivy/Widgets/Internal/SidebarNews.cs, Ivy/Widgets/Internal/Terminal.cs
This pull request primarily removes verbose or redundant XML documentation comments from private methods and properties across several files, focusing on internal implementation details that are not exposed to consumers of the API. The changes help streamline the codebase and reduce clutter, making maintenance easier without affecting functionality or public API documentation.
Documentation cleanup for private/internal methods:
* Removed detailed XML comments from private helper methods in core files such as `AbstractWidget.cs`, `HookExtensions.cs`, and `ViewContext.cs`, simplifying internal code and focusing documentation on public interfaces. [[1]](diffhunk://#diff-2494ab7682719cb5b13c79888f1364575a81b307477efbc0e3873cd015102240L235-L242) …
=> (xml-docs): cleanup

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Callout.md
=> (docs): (Callout): remove additional gap and fix layouts

Ivy.Docs.Shared/Docs/02_Widgets/04_Layouts/ResizeablePanelGroup.md
=> (docs): (ResizeablePanelGroup): fix toc issue and rewrite basic usage example

frontend/src/widgets/inputs/code/CodeInputWidget.tsx, frontend/src/widgets/inputs/code/theme.ts
We didn't have highlighting of selected code, it was unable to see what code is selected. Fixed
=> (CodeInput): implement highlighting of selected code(text)

Ivy.Docs.Shared/Docs/02_Widgets/06_Charts/PieChart.md
=> (docs): (PieChart): fix headings

Ivy.Docs.Shared/Docs/02_Widgets/04_Layouts/SidebarLayout.md
=> (docs): fix headings in SideBarLayout doc

Ivy.Docs.Shared/Docs/02_Widgets/01_Common/Pagination.md, Ivy.Samples.Shared/Apps/Widgets/PaginationApp.cs, Ivy/Widgets/Pagination.cs, frontend/src/components/ui/pagination.tsx, frontend/src/widgets/PaginationWidget.tsx, frontend/src/widgets/index.ts, frontend/src/widgets/widgetMap.ts
Added pagination widget from #733.
@rorychatt please have a look!
Thanks!!
=> (pagination): implement pagination widget

frontend/src/widgets/ExpandableWidget.tsx, frontend/src/widgets/article/DocumentTools.tsx
Need to impplement also copying of Details Summary, will do it tonight
=> (docs): implement copying of Details wrap Examples

Ivy.Samples.Shared/Apps/Concepts/DetailsApp.cs, frontend/src/widgets/details/DetailWidget.tsx, frontend/src/widgets/primitives/TextBlockWidget.tsx
=> (feat): center elements in detals

frontend/src/widgets/inputs/code/theme.ts
=> (UI): reduce code input size to avoid mistaken scrollbar

Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Audio.md, Ivy.Samples.Shared/Apps/Widgets/AudioApp.cs, Ivy.Test/AudioWidgetTests.cs, Ivy/Widgets/Primitives/Audio.cs, frontend/src/widgets/primitives/AudioWidget.tsx, frontend/src/widgets/primitives/index.ts, frontend/src/widgets/widgetMap.ts
as requested by @nielsbosma and @ViktorWb 
This pull request introduces a new `Audio` widget to the Ivy framework, enabling playback of audio files with customizable controls and configuration options. The implementation includes the core widget, extension methods for fluent configuration, frontend rendering logic, documentation, sample usage, and comprehensive unit tests.
**Audio Widget Implementation and API:**
- Added the `Audio` widget (`Audio.cs`) supporting playback of common audio formats, with configurable properties such as `autoplay`, `loop`, `muted`, `preload`, and `controls`. Also includes the `AudioPreload` enum and fluent extension methods for easy property updates.
**Frontend Integration:**
- Implemented the React component `AudioWidget` to render the audio player in the …
=> (audio): implement audio playback widget

Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/03_DatabaseIntegration/01_Overview.md, Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_Auth0.md, frontend/package-lock.json, frontend/package.json, frontend/src/components/MarkdownRenderer.tsx, frontend/src/widgets/article/TableOfContents.tsx
Now linking to other section in the same document works
=> (Docs): enable linking to other sections in docs pages

Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/01_Overview.md, Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_Auth0.md, Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_Authelia.md, Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_BasicAuth.md, Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_MicrosoftEntra.md, Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_Supabase.md
Including making use of new intra-page links feature.
=> (docs): Finish Authelia docs, improve other auth pages

Ivy.Samples.Shared/Apps/Widgets/ButtonApp.cs, Ivy/Widgets/Button.cs, frontend/src/components/ui/button/variants.ts, frontend/src/index.css
- Added new button variants: Success, Warning, Info
- Updated ButtonApp to support and display all variants
- Improved button layout: switched to wrapping layout for better spacing when there are many buttons
- Updated styles to prevent buttons from being squeezed
With more button variants, the previous grid layout was too crowded. Wrapping and spacing improvements make the UI more readable and visually balanced.
=> (button): add new button variants (Success, Warning, Info) and update styles

Ivy/Core/AbstractWidget.cs, Ivy/Core/PropAttribute.cs, Ivy/Shared/MenuItem.cs, Ivy/Views/Forms/FormBuilder.cs, Ivy/Widgets/AudioRecorder.cs, Ivy/Widgets/Badge.cs, Ivy/Widgets/Button.cs, Ivy/Widgets/Chat.cs, Ivy/Widgets/Details/Detail.cs, Ivy/Widgets/DropDownMenu.cs, Ivy/Widgets/Expandable.cs, Ivy/Widgets/Forms/FormField.cs, Ivy/Widgets/Inputs/Option.cs, Ivy/Widgets/Layouts/FloatingPanel.cs, Ivy/Widgets/Lists/ListItem.cs, Ivy/Widgets/Pagination.cs, Ivy/Widgets/Primitives/Article.cs, Ivy/Widgets/Primitives/Html.cs, Ivy/Widgets/Primitives/Kbd.cs, Ivy/Widgets/Primitives/Markdown.cs, Ivy/Widgets/Primitives/TextBlock.cs, Ivy/Widgets/Primitives/Xml.cs, Ivy/Widgets/Progress.cs, Ivy/Widgets/Sheet.cs, Ivy/Widgets/Slot.cs, Ivy/Widgets/Tables/Table.cs, Ivy/Widgets/Tables/TableCell.cs, Ivy/Widgets/Tables/TableRow.cs, Ivy/Widgets/Tooltip.cs
This pull request refactors XML documentation comments across several files to make them more concise and direct, improving readability and maintainability without changing any functional code. The changes focus on shortening summary and parameter descriptions, removing redundant language, and clarifying the purpose of classes, methods, and parameters.
**Documentation comment simplification:**
* [`Ivy/Core/AbstractWidget.cs`](diffhunk://#diff-2494ab7682719cb5b13c79888f1364575a81b307477efbc0e3873cd015102240L8-R40): Shortened and clarified XML documentation comments for the `AbstractWidget` class, its constructor, properties, and methods, including `SetAttachedValue`, `GetAttachedValue`, `Id`, `Key`, `Children`, `Serialize`, `GetPropertyValue`, `InvokeEvent`, and the `|` operator overload. …
=> (feat): minify xml docs

frontend/src/widgets/ProgressWidget.tsx
This pull request makes a minor UI adjustment to the `ProgressWidget` component. The change updates the styling of the goal display by removing the `text-small-label` class and replacing it with the standard `text-sm` class, which will slightly alter the font size and appearance.
=> (progress): UI font adjustments

Ivy.Samples.Shared/Apps/Widgets/Inputs/NumberInputApp.cs, Ivy/Widgets/Inputs/NumberInput.cs, frontend/e2e/number-input.spec.ts, frontend/src/components/NumberInput.tsx, frontend/src/components/ui/input.tsx, frontend/src/components/ui/input/variants.ts, frontend/src/components/ui/slider.tsx, frontend/src/types/sizes.ts, frontend/src/widgets/inputs/NumberInputWidget.tsx
=> (feat): implement Size for number input

frontend/package-lock.json, frontend/package.json
This pull request updates several dependencies in the `frontend/package.json` to their latest versions. These updates help ensure the project benefits from recent bug fixes, performance improvements, and new features provided by these libraries.
Dependency upgrades:
* Upgraded `axios` from version `1.11.0` to `1.12.2` for improved HTTP client functionality and potential bug fixes.
* Upgraded `mermaid` from version `11.10.1` to `11.12.0` to include the latest diagramming features and fixes.
* Upgraded `vite` from version `7.0.6` to `7.1.6` for better build performance and compatibility.
=> (codex): frontend health updates

frontend/src/widgets/layouts/TabsLayoutWidget.tsx, frontend/src/widgets/layouts/sidebar/SidebarLayoutWidget.tsx
Reverts Ivy-Interactive/Ivy-Framework#871
=> Revert "(ui/ux): (tabs): better align toggle button"

Ivy/Widgets/Blades/Blade.cs, frontend/src/lib/styles.ts, frontend/src/widgets/blades/BladeWidget.tsx, frontend/src/widgets/primitives/TextBlockWidget.tsx
=> (blade): smaller min default width; resolve issues for cards with details inside of min width blades

Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/02_Init.md, Ivy.Docs.Shared/Docs/02_Widgets/01_Common/Table.md, Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/AudioPlayer.md
https://github.com/Ivy-Interactive/Ivy-Framework/releases/tag/v1.0.106
Synced docs with release. Provided changes presented with: what was done and where, screenshot from release, sceenshot with changes.
1) Added section to Cli -> Init -> Ivy fix
2) Added section to Cli -> init -> App Removal Command
3) Added example section with controls and size methods usage in Audio Player Widget -> Examples
4) Improved Builder Factory Methods to show Table Multiline in Table ->  Builder Factory Methods
5) Details Widget Multiline Support -> was already implemeneted
6) Audio Recorder Widget -> was already implemeneted
7) Sliplane Deployment Provider -> was already implemeneted
=> [Docs] Sync docs with release v1.0.106

Ivy.Samples.Shared/Apps/Widgets/Inputs/FileInputApp.cs, Ivy/Widgets/Inputs/FileInput.cs, frontend/src/components/ui/input/file-input-variants.ts, frontend/src/widgets/inputs/FileInputWidget.tsx
=> (feat): implement Size for File Input type

Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/05_Deploy.md
=> (docs): Fix incorrect Dockerfile in deployment docs

Ivy.Samples.Shared/Apps/Widgets/Inputs/FeedbackInputApp.cs, Ivy/Widgets/Inputs/FeedbackInput.cs, frontend/src/components/EmojiRating.tsx, frontend/src/components/StarRating.tsx, frontend/src/components/ui/thumbs-rating/ThumbsRating.tsx, frontend/src/widgets/inputs/FeedbackInputWidget.tsx
=> (feat): implement Size for Feedback Input type 

Ivy.Samples.Shared/Apps/Widgets/Inputs/ColorInputApp.cs, Ivy/Widgets/Inputs/ColorInput.cs, frontend/src/components/ui/input/color-input-variants.ts, frontend/src/widgets/inputs/ColorInputWidget.tsx
=> (feat): implement Size for Color Input type

Ivy.Samples.Shared/Apps/Widgets/Inputs/BoolInputApp.cs, Ivy/Widgets/Inputs/BoolInput.cs, frontend/src/components/ui/checkbox.tsx, frontend/src/components/ui/input/bool-input-variants.ts, frontend/src/components/ui/input/switch-variants.ts, frontend/src/components/ui/switch.tsx, frontend/src/components/ui/toggle/toggle-group.tsx, frontend/src/components/ui/toggle/toggle-variants.ts, frontend/src/components/ui/toggle/toggle.tsx, frontend/src/widgets/inputs/BoolInputWidget.tsx
=> (feat): Implement Size for Bool Input

Ivy/Widgets/Primitives/AppHost.cs, Ivy/Widgets/Primitives/Audio.cs, Ivy/Widgets/Primitives/Avatar.cs, Ivy/Widgets/Primitives/Box.cs, Ivy/Widgets/Primitives/Callout.cs, Ivy/Widgets/Primitives/Code.cs, Ivy/Widgets/Primitives/Embed.cs, Ivy/Widgets/Primitives/Empty.cs, Ivy/Widgets/Primitives/Error.cs, Ivy/Widgets/Primitives/Fragment.cs, Ivy/Widgets/Primitives/Icon.cs, Ivy/Widgets/Primitives/Iframe.cs, Ivy/Widgets/Primitives/Image.cs, Ivy/Widgets/Primitives/Json.cs, Ivy/Widgets/Primitives/Loading.cs, Ivy/Widgets/Primitives/Separator.cs, Ivy/Widgets/Primitives/Skeleton.cs, Ivy/Widgets/Primitives/Spacer.cs, Ivy/Widgets/Primitives/Svg.cs
This pull request refactors and streamlines the XML documentation comments for several primitive widget classes in the Ivy framework. The main goal is to make the comments more concise and focused, improving readability and maintainability without changing any functional code.
Documentation simplification and clarity:
* [`Ivy/Widgets/Primitives/AppHost.cs`](diffhunk://#diff-98b647b25aea803522388edca21a18f7d21f575b852fd736384c3de2eea37c08L6-R26): Replaced verbose XML comments with concise summaries for the `AppHost` widget and its properties, focusing on the essential purpose and usage of hosting modular Ivy applications.
* [`Ivy/Widgets/Primitives/Audio.cs`](diffhunk://#diff-0ed731f74997d275233738d01c4e654294778b1bfe64abc16c8fe1e9edc7e8eeL7-R68): Shortened and clarified XML documentation …
=> (codex): xml docs token usage improvements
