README.md

We had `../` as leftover from previous variant, where FE step was after the BE step.
We moved it  around, and now relative pathing might confuse ppl because this is the first step.
My suggestion is to keep the paths without relative navigation not to confuse anyone.

chore: fix confusing relative pathing

---

Ivy/Widgets/Inputs/BoolInput.cs

As discussed some time ago, I remove also support in BE for unsigned numeric types.
Here is what we decided to keep:
```csharp
public Type[] SupportedStateTypes() =>
[
// Boolean types
typeof(bool), typeof(bool?),
// Signed integer types
typeof(short), typeof(short?),
typeof(int), typeof(int?),
typeof(long), typeof(long?),
// Unsigned integer types
typeof(byte), typeof(byte?),
// Floating-point types
typeof(float), typeof(float?),
typeof(double), typeof(double?),
typeof(decimal), typeof(decimal?)
];
```

chore: remove untested bool input vars

---

frontend/.env.development

Not sure why it worked before since we updated BE to run on 5010. 
The only use of the env var is here 
And I guess it has to be configured in `.env`, not in `.env.development`.
But we have had no information on how to use env files and the 5010 port is specified as fallback.

chore: update env vars

---

Ivy.Samples/Apps/Widgets/Inputs/BoolInputApp.cs

`Not Implemented -> N/A`
Made this UX change as we do not plan on implementing this

(boolinput): rename not implemented into N/A

---

frontend/src/widgets/inputs/BoolInputWidget.tsx

- now relying more on flex instead of grid for placing elements in bool input
- the button is now centered relative to label/labels
due to this documentation looks cleaner
This is how it looked before

feat: center bool input for docs

---

frontend/src/widgets/ExpandableWidget.tsx

This had some padding that got attached. I think this was another issue from the update.

feat: expandable remove extra padding

---

frontend/src/widgets/effects/ConfettiWidget.tsx

This pull request enhances the existing ConfettiWidget by introducing a custom "quadrant" shape for confetti particles. The new shape is defined using a specific SVG path, and replaces the default confetti shapes, resulting in a more unique and branded visual effect. Additionally, the color palette has been updated to use new green tones.
- **Added a custom quadrant confetti shape:**
- Introduced a new shape for confetti particles using `confetti.shapeFromPath`.
- The shape is defined by the SVG path: `M47 0H0V47.0222C25.9234 47.0222 47 25.9801 47 0Z`.
- **Updated confetti colors:**
- Changed the confetti color palette to use two specific colors: `#00CC92` and `#0D4A2F`.
- **Modified confetti trigger to use new shape and colors:**
- The `triggerConfetti` function now applies the custom …

Add custom quadrant shape to confetti widget

---

frontend/src/components/MarkdownRenderer.tsx
frontend/src/lib/textBlockClassMap.ts

use common styling for inline codes

---

frontend/src/components/ErrorDisplay.tsx
frontend/src/components/MarkdownRenderer.tsx
frontend/src/lib/ivy-prism-theme.ts
frontend/src/widgets/primitives/CodeWidget.tsx

This brings more consistency in scrollbars in our framework and more
Fixed this to resolve issue with scrollbars moving containers around in Ivy.Docs. 
We got jank before when you hover on a code block

improve usage of scrollbars in code blocks

---

frontend/src/widgets/internal/TerminalWidget.tsx

feat: terminal icon and text is now centered

---

Ivy.Docs.Shared/Docs/02_Widgets/01_Common/Button.md

(docs): remove custom colors section from buttons documentation

---

Ivy/Apps/AppRepository.cs

This fixes unwanted duplication of index groups in the hierarchy. Previously, changing the name of a group in `AddApp()` could break lookup by title in subsequent calls to `GetApp()`.

(code): defer fixup of index group properties

---

Ivy.Docs.Shared/Docs/02_Widgets/02_Inputs/AsyncSelect.md

(doc): delete redundant example in AsyncSelect doc

---

Ivy.Docs.Shared/Docs/03_ApiReference/IvyShared/Icons.md

The issue with centering text was in using Text.Inline, Text.Block or other methods except Text.Label
With Text.Label it's centering perfectly for some reason

(docs): (icons): make available to copy icons to clipboard

---

frontend/src/widgets/layouts/FooterLayoutWidget.tsx

The issues was in the FE part of FooterLayout. Edit Product window is a sheet, and it's content inits as a footer content. Footer sets extra padding for content above, so this change will fix all the sheets visibility, too (I saw this issue in sheet doc, which had footer usage)
Sheets with footer usage now:
The card in it also had extra padding before
And because of it footer with content mentions changed:
I think it's correct and more natural now, btw
@rorychatt , need your thought

(Samples): (Products): fix gaps in product view(edit)

---

Ivy.Samples.Shared/Apps/Widgets/ExpandableApp.cs
frontend/src/widgets/ExpandableWidget.tsx

This pull request introduces improvements to the `Expandable` widget in both the backend sample app and the frontend React component. The main focus is on handling cases where interactive elements (like switches) are present in the expandable header, ensuring they remain usable even when the expandable is disabled, and refining the UI layout for better usability.
**Frontend improvements:**
* Ensured that when the `ExpandableWidget` is disabled, it automatically closes if open, preventing interaction inconsistencies.
* Refactored the header layout in `ExpandableWidget.tsx` to allow embedded interactive elements (such as switches) to remain accessible and visually aligned, even when the expandable is disabled.
**Backend sample app enhancements:**
* Expanded the sample in `ExpandableApp.cs` …

(expandable): resolve disabled data state nested component state mismatch issue

---

Ivy.Docs.Tools/MarkdownConverter.cs
frontend/src/widgets/ExpandableWidget.tsx

This pull request refactors the handling of custom `<Details>` blocks in markdown conversion, ensuring they are parsed and rendered correctly even when the markdown parser fails to recognize them. It also generalizes indentation and context handling for nested markdown/code blocks, improving output formatting and maintainability. Additionally, a minor UI tweak is made to the expandable widget header alignment.
**Markdown `<Details>` block parsing and rendering improvements:**
* Added manual detection and processing of `<Details>` blocks using regular expressions, allowing for correct handling even when the markdown parser does not parse them as a single block. The new logic skips nested content inside `<Details>` for standard markdown processing and extracts summary/body content for …

(docs): add support for expandable element

---

frontend/src/index.css
frontend/src/widgets/ExpandableWidget.tsx

This pull request updates the expand/collapse animation and icon behavior in the `ExpandableWidget` component, and introduces new CSS keyframes for collapsible transitions. The main changes improve the UI consistency and animation smoothness for expanding and collapsing widgets.
**Animation and UI improvements:**
* Added new `collapsible-down` and `collapsible-up` keyframes to `frontend/src/index.css` to animate both height and opacity for collapsible content transitions.
* Updated theme variables to use the new collapsible animations and shortened animation durations for both accordion and collapsible transitions in `frontend/src/index.css`.
* Changed the expand/collapse icon in `ExpandableWidget.tsx` to use a single `ChevronRight` icon that rotates when open, replacing the previous …

(expandable): add cool animations

---

Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_BasicAuth.md

Goes with new fix in Ivy.Console. Also makes this part of the basic auth page more consistent with that of the Entra page.

(docs): `JWT_ISSUER`, `JWT_AUDIENCE` can now be set in connection string

---

frontend/src/widgets/internal/DbmlCanvasWidget.css
frontend/src/widgets/internal/DbmlCanvasWidget.tsx

(feat): (DBML): handle connection line and edges in different themes

---

frontend/src/components/ui/resizable.tsx

While isn't active:
On hovering:
(cursor isn't visible on screenshots)

(UI): implement better handling of ScrollBar in resizeables

---

Ivy.Samples.Shared/Apps/Demos/DashboardApp.cs

There is no need to use Text.H3 in content of cards, because this class of text has margin that brake horizontal layout

(UI): fix text usage in the cards

---

frontend/src/widgets/primitives/TextBlockWidget.tsx

This pull request makes a small change to the `TextBlockWidget.tsx` component, updating the font size for the `Muted` text variant to use the `text-sm` class instead of `text-large-body`. This change ensures muted text appears smaller and more consistent with typical UI patterns.

(jobs): typography updates, smaller fonts

---

Ivy.Docs.Shared/Docs/02_Widgets/02_Inputs/Audio.md
Ivy.Samples.Shared/Apps/Widgets/Inputs/Audio.cs
Ivy/Widgets/AudioRecorder.cs
frontend/src/widgets/AudioRecorderWidget.tsx
frontend/src/widgets/widgetMap.ts

Implements an audio recorder widget, for #769.
The widget supports streaming uploads so that if client is at any point disconnected the so-far uploaded data can still be played.
When recording, the widget displays the volume input to give feedback to the user that the microphone is picking up the audio.

(audio): implement audio recording widget

---

Ivy/Chrome/DefaultSidebarChrome.cs

This pull request introduces a minor UI improvement to the sidebar layout in `DefaultSidebarChrome.cs`. The change adds a small vertical gap between elements in the sidebar for better visual separation.
* UI enhancement: Added a `.Gap(2)` to the `Layout.Vertical()` call in the sidebar layout, which increases spacing between stacked components.

(default-chrome): better gaps in header

---

Ivy.Docs.Shared/Docs/01_Onboarding/02_Concepts/Forms.md
Ivy/Views/Forms/FormBuilder.cs
frontend/src/widgets/forms/FormFieldWidget.tsx

This pull request updates the form layout logic and documentation to clarify and improve how fields are arranged in forms, both in backend form builder methods and frontend rendering. The changes make the intent of horizontal and vertical field placement more explicit, improve code comments, and enhance the flexibility of form layouts.
**Form layout API improvements:**
* Updated the documentation and method signatures in `FormBuilder.cs` to clarify the difference between vertical stacking and horizontal side-by-side arrangement of fields using the `Place` methods. The new comments make it clear when fields are distributed across a row or stacked in a column.
**Form layout usage and examples:**
* Changed the example usage in `Forms.md` to use the new `Place(true, ...)` syntax for arranging …

(forms): better use cases of Place

---

Ivy.Samples.Shared/Apps/Demos/DashboardApp.cs
frontend/src/widgets/charts/PieChartWidget.tsx

This pull request adds a new donut chart view to the dashboard and refactors the frontend pie chart widget to improve how the total value and label are displayed. The main changes are the introduction of a new chart component for displaying budget breakdowns with custom labels, and a frontend update to show the total value and label outside of the chart for better clarity and flexibility.
**Dashboard enhancements:**
* Added a new `DonutChartWithCustomLabelsView` to the dashboard, providing a detailed budget breakdown with custom inner and outer labels, color scheme, legend, and animated tooltip.
* Updated the dashboard layout to include the new donut chart, expanding the grid from 3 to 4 columns for better visual balance.
**Frontend chart widget improvements:**
* Refactored …

(piechart): design rework to better display totals

---

frontend/src/widgets/layouts/TabsLayoutWidget.tsx
frontend/src/widgets/layouts/sidebar/SidebarLayoutWidget.tsx

This pull request makes minor UI adjustments to spacing and positioning in the tab and sidebar layouts to improve visual alignment.
*Tabs layout spacing:*
- Increased the top margin of the `TabsList` component in `TabsLayoutWidget.tsx` from `mt-2.5` to `mt-4` for improved spacing above the tabs.
*Sidebar toggle button positioning:*
- Adjusted the top margin of the sidebar toggle button from `top-2` to `top-3` and shifted its left position by 1px (from `8px`/`calc(16rem + 8px)` to `9px`/`calc(16rem + 9px)`) for better alignment with the sidebar.

(ui/ux): (tabs): better align toggle button

---

Ivy.Docs.Shared/Docs/01_Onboarding/01_GettingStarted/06_ChatTutorial.md
Ivy.Docs.Shared/Docs/01_Onboarding/02_Concepts/Forms.md
Ivy.Docs.Shared/Docs/01_Onboarding/02_Concepts/Signals.md
Ivy.Docs.Shared/Docs/02_Widgets/07_Advanced/Chat.md
Ivy.Samples.Shared/Apps/Demos/LucideIconAgentApp.cs
Ivy/Auth/DefaultAuthApp.cs
Ivy/Chrome/DefaultSidebarChrome.cs
Ivy/Core/Event.cs
Ivy/Views/Forms/UseForm.cs
Ivy/Views/ViewHelpers.cs

This pull request refactors all asynchronous event handlers and callbacks throughout the codebase to use `ValueTask`-returning methods instead of `async void` or `async` lambdas. This change improves error handling, composability, and testability of async code. Additionally, obsolete extension methods for converting action handlers to event handlers have been removed to encourage the new pattern. The changes affect onboarding tutorials, authentication flows, form handling, signal demos, chat examples, and helper utilities.
**Async event handler refactoring:**
* Converted all `async void` event handlers and callbacks in onboarding tutorials (`Forms.md`, `Signals.md`, `ChatTutorial.md`), chat demos (`Chat.md`), authentication flows (`DefaultAuthApp.cs`), and sample apps …

(health): cleanup memory leaks

---

frontend/src/widgets/layouts/sidebar/SidebarLayoutWidget.tsx

This pull request makes minor adjustments to the styling of the sidebar layout widget in the frontend. The changes remove the border styles from the sidebar header and footer sections for a cleaner appearance.

(sidebar): remove borders around main content

---

Ivy.Docs.Shared/Docs/01_Onboarding/02_Concepts/Forms.md
Ivy/Views/Forms/FormBuilder.cs
Ivy/Views/Forms/FormExtensions.cs

It allows the user to pass the text that is in the submit button directly in the toForm() method without having to do more work, I think it is usefull because other wise he would have to create the button himself and handle the click
Code example
Result:

Allow custom submit title in toForm() method

---

Ivy.Docs.Shared/Docs/01_Onboarding/02_Concepts/Secrets.md
Ivy.Docs.Shared/Docs/04_Concepts/_index.md

https://github.com/Ivy-Interactive/Ivy-Framework/pull/925
"! We need to reorder this section in sidebar of doc page, because i didn't find where ordering of docs is defined"
I asked not to merge that PR until this doc won't have right placement with other docs
This PR is a small fix of its placement
Now it's with other concepts
Deleted created folder "04_Concepts" from mentioned PR
Also renamed file

[Docs]: fix Secrets doc placement in sidebar with apps

---

Ivy.Samples.Shared/Apps/Widgets/Inputs/DateTimeInputApp.cs
Ivy/Widgets/Inputs/DateTimeInput.cs
frontend/src/components/ui/calendar/calendar-variants.ts
frontend/src/components/ui/calendar/calendar.tsx
frontend/src/components/ui/input/date-time-input-variants.ts
frontend/src/widgets/inputs/DateTimeInputWidget.tsx

(feat): Implement Size for DateTime Input type

---

frontend/package-lock.json
frontend/package.json
frontend/src/widgets/charts/PieChartWidget.tsx
frontend/src/widgets/charts/shared.ts
frontend/vite.config.ts

This pull request updates the `recharts` charting library to version 3.2.1 and makes several related improvements and fixes to chart widget typings and build configuration. The changes ensure better compatibility with the new `recharts` version and optimize how chart-related code is bundled.
**Dependency update and compatibility adjustments:**
- Upgraded `recharts` from version 3.1.2 to 3.2.1 in both `package.json` and `package-lock.json` for improved features and bug fixes. [[1]](diffhunk://#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655L88-R88) [[2]](diffhunk://#diff-4a2d9aa3e849b134993936ca81b83fb139edd2b0218077ab0f403b8c4803c62aL81-R81) [[3]](diffhunk://#diff-4a2d9aa3e849b134993936ca81b83fb139edd2b0218077ab0f403b8c4803c62aL10126-R10128)
**Type and props …

(rechart): fix support for react 19

---

Ivy.Samples.Shared/Apps/Demos/ProductsApp.cs
frontend/src/widgets/blades/BladeWidget.tsx

This pull request introduces a small frontend layout improvement and a significant change to the `ProductDetailsBlade` in the backend. The backend now returns a vertical layout containing multiple instances of the product details card, likely for demonstration or testing purposes.
Backend: Product details blade changes
* Refactored the `ProductDetailsBlade` to create a `productCard` variable and return a vertical layout containing five instances of the product card, each separated by a gap. [[1]](diffhunk://#diff-5277a8877c9dc966be0aaaeb22375ca70940fcf5b44d2275ec2d254ca42bd356L120-R120) [[2]](diffhunk://#diff-5277a8877c9dc966be0aaaeb22375ca70940fcf5b44d2275ec2d254ca42bd356R135-R143)
Frontend: Layout improvement
* Updated the `BladeWidget` container to use `flex-1 min-h-0` instead of a …

(blade): scroll fix for radix scrollarea with nested elements

---

Ivy.Samples.Shared/Apps/Widgets/Inputs/SelectInputApp.cs
Ivy.Test/JsonEnumConverterTests.cs
Ivy/Core/Helpers/JsonEnumConverter.cs

This pull request addresses a serialization bug with enums that have `Description` attributes, ensuring that enum values are always serialized as their names (not their descriptions) and deserialized correctly. It also adds a new UI test section to demonstrate label/value edge cases for select inputs, and introduces comprehensive unit tests to verify the new serialization behavior.
**Enum Serialization Fixes and Tests:**
* Updated `JsonEnumConverter` so that enums are always serialized as their name (e.g., `"SnakeCase"`), not their `Description` attribute, fixing an issue where the frontend received the wrong value and could not round-trip enum values correctly.
* Added a new test suite `JsonEnumConverterTests` to verify that serialization and deserialization of enums work as intended, …

(select): resolve value mismatch 

---

frontend/src/widgets/inputs/NumberInputWidget.tsx

Fixes : #912 
- Updated frontend/src/widgets/inputs/NumberInputWidget.tsx to remove hard-coded defaults min=0 and max=100 for the Number variant.
- The widget now clamps values only when min and/or max are explicitly provided via props.
- Preserved Slider variant defaults (min=0, max=100) to avoid breaking existing usage; slider end-labels now render only when both bounds are provided.
- Type-level bounds validation via validateAndCapValue() remains in place to prevent overflow for numeric target types.

(number input): respect provided min/max instead of hard-coded 0/100

---

Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/03_DatabaseIntegration/01_Overview.md
Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/03_DatabaseIntegration/02_SQLite.md
Ivy.Docs.Shared/Docs/02_Widgets/03_Primitives/Image.md

1. No need to be included in the documentation.
2. No need to be included in the documentation.
3. Docs -> Cli -> Database Integration -> New section "Default Schema"
4. Do we need to docement it externally? 
5. Docs -> Cli -> Database Integration -> New section "Entity Framework Migrations"
6. No need to be included in the documentation(?)
SQLite has it's own documentation, but there is no code provided in doc, so it seems not to be there.
7. No need to be included in the documentation.
In the most of input widgets we have API sections in docs with Size props.
8. This doesn't actually works? 
9. Docs -> Image -> new section "Supported Image Sources"
10. Already in Docs, Pie chart -> Donut Chart with Custom Labels
11.  No need to be included in the documentation.

[Docs]: Sync docs with Release 1.0.114

---

Ivy.Auth.Auth0/Auth0AuthProvider.cs
Ivy.Docs.Shared/Docs/01_Onboarding/03_CLI/04_Authentication/02_Auth0.md

This PR changes how the Auth0 provider handles JWTs, and how it gets the user info. Instead of using the Auth0 Authentication API, the JWT is verified using the Auth0 JWKS, and user info (id, email, name, etc.) is read straight from the JWT claims.
Issue #988

(auth0): support direct JWT verification

---

frontend/src/widgets/charts/shared.ts

Old one:
New one:
In light theme:

[PieChart]: Redefine fill color for label list
